Fix typo
samu92dls/hyperblog pull request #1
Opened 2021-07-08 09:15 UTC by samu92dls

no debimos dejar pasar este error al master

2021-07-08 09:25 UTC, SamuAnita commented
corrija las letras mal colocadas

2021-07-08 09:30 UTC, SamuAnita requested changes
cambia las letras

2021-07-08 09:34 UTC, samu92dls commented
cambios hechos por favor hazme el merge

2021-07-08 09:35 UTC, merged

2021-07-10 09:31 UTC, samu92dls reviewed
ok